### ISSUE TITLE
trailing "1"?

### ISSUE THREAD

**Issue by ratnanil** [ratnanil/burningData#5]
Hey @KimboGilda : What are these `1` on the following lines?

https://github.com/ratnanil/burningData/blob/614613cbd555e1f34663f2a16fbce6c0eef954cb/R/data.R#L47
https://github.com/ratnanil/burningData/blob/614613cbd555e1f34663f2a16fbce6c0eef954cb/R/data.R#L62
https://github.com/ratnanil/burningData/blob/614613cbd555e1f34663f2a16fbce6c0eef954cb/R/data.R#L81

**Comment by KimboGilda** [comment]
@ratnanil  Nothing exactly -- I will remove it
