### ISSUE TITLE
repo transferred

### ISSUE THREAD

**Issue by ratnanil** [ratnanil/burningData#7]
@KimboGilda : Note that this is the new repo for the package. Please adjust your upstream / remote and close this issue when successful. 

note, I will adjust the package name accordingly (see #6 )

**Comment by ratnanil** [comment]
I had to rename the repo again due to a technical issue. please adjust your upstream / remoet and close this issue when successful.

**Comment by KimboGilda** [comment]
> 
> 
> I had to rename the repo again due to a technical issue. please adjust your upstream / remoet and close this issue when successful.

@ratnanil I adjusted it accordingly. So, I am closing this one

**Comment by ratnanil** [comment]
just to document: 

```
remote: This repository moved. Please use the new location:        
remote:   git@github.com:arc2r/arc2r.git  
```` 
this is solved by 


```
git remote set-url origin git@github.com:arc2r/arc2r.git
```
